### ISSUE TITLE
Can I add custom tokens to be used in bridge?

### ISSUE THREAD

**Issue by zydjohnHotmail** [allbridge-io/allbridge-core-js-sdk#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I saw on your brige web page: https://app.allbridge.io/bridge.
People can send tokens from TerraClassic to Solana, which is what I want to do, but the specific token is not in the list, its symbol is: 'PRISM'
Its contract address can be found here:
https://etherscan.io/token/0xd46df541148932690b81092f600f35208afd4325

I want to know if it is possible give users a chance to add custom tokens, like PRISM, since I have the contract address, I think this should be possible.

**Describe alternatives you've considered**
I took a look at Wormhole bridge, they seemed to have the same bridge before, but the TerraClassic is under software update, it has been a while already, no idea when it can be done.  Just remind me that one crypto exchange AAX, the stuff told me that they were doing some wallet mainenance, until after one month, I found the exchange shutdown and bankrupt, and many people lost a lot of money.  Hope this software upgrade is not that bad.

**Additional context**

It will be great that SDK/API can provide some interface, so for developers, can also add some custom tokens.  There are thousands of tokens, for web page, no matter how many tokens are on the list, people will always need more.
Therefore, please open a door for the people who need more tokens to be added.
Thanks,

**Comment by Kozer4** [comment]
HI, Sorry for taking so long to reply, I'll try to fix it in the future

This SDK build for a different product([Core Bridge](https://core.allbridge.io/)) other than what you described (https://app.allbridge.io/bridge)

no custom token mechanism will be implemented, only what is supported by ([Core Bridge](https://core.allbridge.io/))
