### ISSUE TITLE
Can't approve the transaction

### ISSUE THREAD

**Issue by burbinagomez** [allbridge-io/allbridge-core-js-sdk#76]
**Describe the bug**
Using the example provided for swapping between two chains, I encounter an 'Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'chainType')' when trying to invoke sdk.bridge.approve()

**To Reproduce**

1. 
2.
3.

**Expected behavior**
I want so sign and continue with the flow

**Screenshots**
![image](https://github.com/allbridge-io/allbridge-core-js-sdk/assets/51467293/da998003-b9b9-4326-b151-0ff38b8a9165)
![image](https://github.com/allbridge-io/allbridge-core-js-sdk/assets/51467293/705ea405-59d8-4b2e-b331-98d4ba52e891)

**Desktop (please complete the following information):**

- OS: [e.g. Ubuntu 22.04, macOS 11.4]
- Node version [e.g 16.4.2]
- Code Version [e.g. 1.1.0]

**Additional context**

**Comment by Kozer4** [comment]
Hello
first of all please use the latest version of SDK (3.9.1)

take a closer look at the required types:
```
export interface ApproveParams {
  /**
   * The token info
   */
  token: TokenWithChainDetails;
```
token is TokenWithChainDetails not String
please remove ".tokenAddress" and try again
